### ISSUE TITLE
Socket option Dont Fragment not supported on MacOS

### ISSUE THREAD

**Issue by roordaj** [ela-compil/BACnet#91]
When using the library on MacOS, I get the following error:

Unhandled exception. System.Net.Sockets.SocketException (45): Operation not supported
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.SetSocketOption(SocketOptionLevel optionLevel, SocketOptionName optionName, Int32 optionValue, Boolean silent)
   at System.Net.Sockets.Socket.SetSocketOption(SocketOptionLevel optionLevel, SocketOptionName optionName, Int32 optionValue)
   at System.Net.Sockets.Socket.set_DontFragment(Boolean value)
   at System.Net.Sockets.UdpClient.set_DontFragment(Boolean value)
   at System.IO.BACnet.BacnetIpUdpProtocolTransport.Open()
   at System.IO.BACnet.BacnetIpUdpProtocolTransport.Start()
   at System.IO.BACnet.BacnetClient.Start()

This is because the MacOS socket does not support that option. A solution might be to omit the setting when not specified explicitly in the constructor.

**Comment by YarekTyshchenko** [comment]
Should be fixed by #116 Can you check with the latest version of the lib?

**Comment by gralin** [comment]
Fixed in **4.0.0-beta.1**: OS detection now uses `RuntimeInformation.IsOSPlatform` instead of `Environment.OSVersion.Platform`, so the DontFragment guard is correctly skipped on macOS.
